// Generated by Wrangler on Fri Sep 13 2024 12:16:05 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	POSTGRES_DB: string;
	POSTGRES_USER: string;
	POSTGRES_PASSWORD: string;
	DB_URL: string;
	AI: Ai;
}
